[package]
name = "syrette"
version = "0.2.1"
license = "MIT OR Apache-2.0"
authors = ["HampusM <hampus@hampusmat.com>"]
description = "The convenient dependency injection library"
repository = "https://git.hampusmat.com/syrette"
keywords = ["DI", "dependency-injection", "ioc", "inversion-of-control"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[features]
factory = ["syrette_macros/factory"]

[[example]]
name = "factory"
required-features = ["factory"]

[dependencies]
syrette_macros = { path = "./macros", version = "0.2.1" }
linkme = "0.3.0"
once_cell = "1.4"
error-stack = "0.1.1"
ahash = "0.7.6"

[dev_dependencies]
mockall = "0.11.1"

[workspace]
members = [
	"macros",
]

