[package]
name = "syrette"
version = "0.1.0"
license = "LGPL-2.1"
authors = ["HampusM <hampus@hampusmat.com>"]
description = "The convenient dependency injection library"
repository = "https://git.hampusmat.com/syrette"
keywords = ["DI", "dependency-injection", "ioc", "inversion-of-control"]
edition = "2021"

[features]
factory = []

[[example]]
name = "factory"
required-features = ["factory"]

[dependencies]
syrette_macros = { path = "./macros", version = "0.1.0" }
linkme = "0.3.0"
once_cell = "1.4"
error-stack = "0.1.1"

[dev_dependencies]
mockall = "0.11.1"

[workspace]
members = [
	"macros",
]

