[package]
name = "syrette"
version = "0.2.1"
license = "MIT OR Apache-2.0"
authors = ["HampusM <hampus@hampusmat.com>"]
description = "The convenient dependency injection library"
repository = "https://git.hampusmat.com/syrette"
keywords = ["DI", "dependency-injection", "ioc", "inversion-of-control"]
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["prevent-circular"]
factory = ["syrette_macros/factory"]
prevent-circular = ["syrette_macros/prevent-circular"]

[[example]]
name = "factory"
required-features = ["factory"]

[[example]]
name = "with-3rd-party"
required-features = ["factory"]

[dependencies]
syrette_macros = { path = "./macros", version = "0.2.1" }
linkme = "0.3.0"
once_cell = "1.4"
ahash = "0.7.6"
thiserror = "1.0.32"
strum = "0.24.1"
strum_macros = "0.24.3"

[dev_dependencies]
mockall = "0.11.1"
third-party-lib = { path = "./examples/with-3rd-party/third-party-lib" }

[workspace]
members = [
	"macros",
	"examples/with-3rd-party/third-party-lib"
]

