max_width = 90
brace_style = "AlwaysNextLine"
group_imports = "StdExternalCrate"
wrap_comments = true
comment_width = 90
format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
newline_style = "Unix"
reorder_impl_items = true

