version: 2.1

jobs:
  test-all:
    docker:
      - image: cimg/rust:1.63.0
    steps:
      - checkout
      - run: cargo --version
      - run: rustup install nightly
      - run: rustup default nightly
      - run:
          name: Run Tests
          command: cargo test --workspace --all-features
  coverage:
    machine: true
    steps:
      - checkout
      - run:
          name: Code Coverage
          command: |
            docker run \
              --security-opt seccomp=unconfined \
              -v "${PWD}:/volume" \
              xd009642/tarpaulin:0.22.0-nightly \
              cargo \
                +nightly \
                tarpaulin \
                --workspace \
                --all-features \
                --ciserver circle-ci \
                --coveralls $COVERALLS_REPO_TOKEN

workflows:
  test:
    jobs:
      - test-all
      - coverage

