style: none
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://git.hampusmat.com/syrette
options:
  sort: "semver"
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - style
        - chore
        - build
        - docs
        - test
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      style: Style Improvements
      chore: Chores
      build: Build System/Dependency Changes
      docs: Documentation Changes
      test: Code Testing
  header:
    pattern: "^(\\w*)!?(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
