[package]
name = "syrette_macros"
version = "0.2.1"
license = "MIT OR Apache-2.0"
authors = ["HampusM <hampus@hampusmat.com>"]
description = "Macros for Syrette, the convenient dependency injection library"
repository = "https://git.hampusmat.com/syrette"
keywords = ["DI", "dependency-injection", "ioc", "inversion-of-control"]
edition = "2021"

[lib]
proc_macro = true

[package.metadata.docs.rs]
all-features = true

[features]
factory = []

[dependencies]
syn = { version = "1.0.96", features = ["full"] }
quote = "1.0.18"
proc-macro2 = "1.0.40"
uuid = { version = "0.8", features = ["v4"] }

[dev_dependencies]
syrette = { version = "0.2.1", path = "..", features = ["factory"] }
