[package]
name = "syrette_macros"
version = "0.1.0"
license = "LGPL-2.1"
authors = ["HampusM <hampus@hampusmat.com>"]
description = "Macros for Syrette, the convenient dependency injection library"
edition = "2021"

[dependencies]
